# -*- coding:utf-8 -*-

"""
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal
 numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48,
 is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are 
pentagonal and D = |Pk − Pj| is minimised; what is the value of D?


"""

from math import sqrt
def is_square(i):
	return int(sqrt(i)) ** 2 == i
def condition(i):
	a = 1 + 12 * i
	if is_square(a) and (1 + int(sqrt(a)) ) % 6 == 0:
		return True
	return False

if __name__ == "__main__":
	for j in xrange(1,10000):
		for i in xrange(j + 1,10000):
			a = i * ( 3 * i - 1 )
			b = j * ( 3 * j - 1 )
			A =  a + b
			B =  a - b
			if condition(A) and condition(B):
				print i,j

# 满足条件的i,j为2167,1020
# Answer:5482660
